(() => {
  'use strict';
  const URLS={all:'https://raw.githubusercontent.com/setoxxx/nycif-live-feeds/main/nycif_all_radar_map_events.json',major:'https://raw.githubusercontent.com/setoxxx/nycif-live-feeds/main/nycif_major_radar_map_events.json',delta:'https://raw.githubusercontent.com/setoxxx/nycif-live-feeds/main/data/live_delta_report.json'};
  const KEYS={seen:'nycif-calendar-seen-v1',reviewed:'nycif-calendar-reviewed-v1'};
  const state={events:[],majorIds:new Set(),deltaIds:new Set(),sessionNew:new Set(),seen:new Set(),reviewed:new Set(),storage:true,monthOffset:0,selectedDate:'',loadedAt:null,skipped:0,filters:{q:'',borough:'',status:'',category:'',major:false,photo:false}};
  const $=id=>document.getElementById(id),statusNames={new:'New / unreviewed',good:'Good assignment',review:'Needs review',standard:'Standard event'};
  function loadSet(key){try{return new Set(JSON.parse(localStorage.getItem(key)||'[]'))}catch{state.storage=false;return new Set()}}
  function saveSet(key,set){if(!state.storage)return;try{localStorage.setItem(key,JSON.stringify([...set].slice(-100000)))}catch{state.storage=false}}
  function text(v){return String(v??'').trim()} function bool(v){return v===true||v===1||/^true|yes|1$/i.test(text(v))}
  function first(row,names){for(const n of names)if(row?.[n]!==undefined&&row[n]!==null&&text(row[n]))return row[n];return''}
  function isoDate(value){const raw=text(value),m=raw.match(/^(\d{4}-\d{2}-\d{2})/);if(m)return m[1];const d=new Date(raw);if(Number.isNaN(d.getTime()))return'';return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function eventId(row,date,title,location){const raw=first(row,['id','event_id','source_event_id','eventId','sourceEventId']);return text(raw)||`${date}|${title}|${location}`.toLowerCase().replace(/\s+/g,' ').slice(0,300)}
  function normalize(row){const date=isoDate(first(row,['date','start_date','startDate','start_date_time','startDateTime'])),title=text(first(row,['title','event_name','eventName']))||'Untitled event',location=text(first(row,['display_location','location','event_location','locationName','address'])),bv=first(row,['borough','event_borough','eventBorough','boroughs']),borough=Array.isArray(bv)?bv.join(', '):text(bv);if(!date)return null;const id=eventId(row,date,title,location);return{raw:row,id,date,title,location,borough,start:text(first(row,['start_time','startTime'])),end:text(first(row,['end_time','endTime'])),category:text(first(row,['lane','category','event_type','eventType']))||'General',source:text(first(row,['source','source_name','sourceName','source_file','sourceFile']))||'Unknown',verification:text(first(row,['verification_status','verificationStatus'])),priority:Number(first(row,['priority_score','priorityScore']))||0,crowd:text(first(row,['crowd_level','crowdLevel'])),reason:text(first(row,['major_reason','majorReason','review_reason','reviewReason','warning','warnings'])),photo:bool(first(row,['photo_pick','photoPick'])),major:text(first(row,['assignment_feed','assignmentFeed'])).toLowerCase()==='major'||bool(first(row,['field_default','fieldDefault'])),maps:text(first(row,['google_maps_url','googleMapsUrl'])),url:text(first(row,['url','event_url','source_url','sourceUrl']))}}
  function addedIds(delta){const out=new Set();for(const row of Array.isArray(delta?.added_events)?delta.added_events:[]){const n=normalize(row);if(n)out.add(n.id);const d=first(row,['id','event_id','source_event_id','eventId']);if(text(d))out.add(text(d))}return out}
  function needsReview(e){const v=`${e.verification} ${e.reason}`.toLowerCase();return!e.title||e.title==='Untitled event'||!e.location||!e.borough||/(review|uncertain|unverified|pending|rejected|quarantine|warning|invalid)/.test(v)}
  function goodAssignment(e){const v=e.verification.toLowerCase();return e.major||state.majorIds.has(e.id)||e.photo||e.priority>=80||!!e.reason||/(field.intel|verified|confirmed|nypd)/.test(v)}
  function statusOf(e){const isNew=!state.reviewed.has(e.id)&&(state.deltaIds.has(e.id)||state.sessionNew.has(e.id));if(isNew)return'new';if(needsReview(e))return'review';if(goodAssignment(e))return'good';return'standard'}
  function filteredEvents(){const f=state.filters;return state.events.filter(e=>{const hay=`${e.title} ${e.location} ${e.borough} ${e.source} ${e.category}`.toLowerCase();return(!f.q||hay.includes(f.q))&&(!f.borough||e.borough===f.borough)&&(!f.category||e.category===f.category)&&(!f.status||statusOf(e)===f.status)&&(!f.major||e.major||state.majorIds.has(e.id))&&(!f.photo||e.photo)})}
  function monthStart(offset){const now=new Date();return new Date(now.getFullYear(),now.getMonth()+offset,1)} function monthKey(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`} function dateKey(d){return`${monthKey(d)}-${String(d.getDate()).padStart(2,'0')}`}
  function visibleRange(){const first=monthStart(state.monthOffset),after=monthStart(state.monthOffset+2);return[dateKey(first),dateKey(new Date(after.getFullYear(),after.getMonth(),0))]}
  function groupByDate(events){const map=new Map();for(const e of events){if(!map.has(e.date))map.set(e.date,[]);map.get(e.date).push(e)}for(const rows of map.values())rows.sort((a,b)=>`${a.start} ${a.title}`.localeCompare(`${b.start} ${b.title}`));return map}
  function make(tag,cls,value){const el=document.createElement(tag);if(cls)el.className=cls;if(value!==undefined)el.textContent=value;return el}
  function renderMonth(start,grouped){const card=make('section','month-card');card.append(make('h2','month-title',start.toLocaleDateString([],{month:'long',year:'numeric'})));const weekdays=make('div','weekday-row');['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(x=>weekdays.append(make('div','weekday',x)));card.append(weekdays);const grid=make('div','month-grid'),firstDay=new Date(start.getFullYear(),start.getMonth(),1),last=new Date(start.getFullYear(),start.getMonth()+1,0),cursor=new Date(firstDay);cursor.setDate(cursor.getDate()-firstDay.getDay());const end=new Date(last);end.setDate(end.getDate()+(6-last.getDay()));const today=dateKey(new Date());while(cursor<=end){const key=dateKey(cursor),rows=grouped.get(key)||[],btn=make('button','day-cell');btn.type='button';btn.dataset.date=key;btn.setAttribute('aria-label',`${cursor.toLocaleDateString([],{month:'long',day:'numeric',year:'numeric'})}: ${rows.length} events`);if(cursor.getMonth()!==start.getMonth())btn.classList.add('other-month');if(key===today)btn.classList.add('today');if(key===state.selectedDate)btn.classList.add('selected');const top=make('div','day-top');top.append(make('span','day-number',cursor.getDate()),make('span','event-count',`${rows.length} event${rows.length===1?'':'s'}`));btn.append(top);rows.slice(0,3).forEach(e=>{const s=statusOf(e);btn.append(make('span',`event-chip ${s}`,`${s==='new'?'NEW · ':''}${e.start?e.start+' · ':''}${e.title}`))});if(rows.length>3)btn.append(make('span','more-label',`+ ${rows.length-3} more`));btn.addEventListener('click',()=>{state.selectedDate=key;renderAll();$('dailyEvents').scrollIntoView({behavior:'smooth',block:'start'})});grid.append(btn);cursor.setDate(cursor.getDate()+1)}card.append(grid);return card}
  function escapeHtml(v){return text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function eventCard(e){const s=statusOf(e),card=make('article',`event-card ${s}`),head=make('div','event-card-header');head.append(make('h3','',e.title),make('span',`status-label ${s}`,statusNames[s]));card.append(head);const meta=make('div','event-meta'),fields=[['Time',[e.start,e.end].filter(Boolean).join('–')||'Time not listed'],['Borough',e.borough||'Missing'],['Location',e.location||'Missing'],['Category',e.category],['Source',e.source],['Verification',e.verification||'Not listed'],['Priority',e.priority||'—'],['Crowd',e.crowd||'—'],['Assignment reason',e.reason||'—']];fields.forEach(([k,v])=>{const d=make('div','');d.innerHTML=`<strong>${escapeHtml(k)}:</strong> ${escapeHtml(v)}`;meta.append(d)});card.append(meta);const actions=make('div','event-actions');if(e.maps){const a=make('a','','Open map');a.href=e.maps;a.target='_blank';a.rel='noopener noreferrer';actions.append(a)}if(e.url){const a=make('a','','Open source');a.href=e.url;a.target='_blank';a.rel='noopener noreferrer';actions.append(a)}const reviewed=state.reviewed.has(e.id),btn=make('button','',reviewed?'Reviewed in this browser':'Mark reviewed');btn.type='button';btn.disabled=reviewed;btn.addEventListener('click',()=>{state.reviewed.add(e.id);saveSet(KEYS.reviewed,state.reviewed);renderAll()});actions.append(btn);card.append(actions);return card}
  function renderDaily(events){const root=$('dailyEvents');root.replaceChildren();if(!state.selectedDate){root.append(make('div','empty-state','Select a date to open the Daily Blotter.'));$('markAllReviewed').disabled=true;return}const rows=events.filter(e=>e.date===state.selectedDate),d=new Date(`${state.selectedDate}T12:00:00`);$('dailyDateLabel').textContent=d.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('dailySummary').textContent=`${rows.length} matching event${rows.length===1?'':'s'} on this date.`;$('markAllReviewed').disabled=!rows.length;if(!rows.length){root.append(make('div','empty-state','No events match the active filters for this date.'));return}rows.forEach(e=>root.append(eventCard(e)))}
  function renderMetrics(events){const[min,max]=visibleRange(),visible=events.filter(e=>e.date>=min&&e.date<=max),counts={new:0,good:0,review:0,standard:0};visible.forEach(e=>counts[statusOf(e)]++);const values=[['Loaded',state.events.length],['Visible range',visible.length],['New',counts.new],['Good',counts.good],['Needs review',counts.review],['Standard',counts.standard],['Skipped',state.skipped]],root=$('statusMetrics');root.hidden=false;root.replaceChildren();values.forEach(([k,v])=>{const m=make('div','metric');m.append(make('strong','',Number(v).toLocaleString()),make('span','',k));root.append(m)})}
  function renderAll(){const events=filteredEvents(),grouped=groupByDate(events),root=$('calendarMonths');root.replaceChildren(renderMonth(monthStart(state.monthOffset),grouped),renderMonth(monthStart(state.monthOffset+1),grouped));renderDaily(events);renderMetrics(events)}
  function populateFilters(){const add=(id,values)=>{const select=$(id),current=select.value;while(select.options.length>1)select.remove(1);[...new Set(values.filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;select.append(o)});select.value=current};add('boroughFilter',state.events.map(e=>e.borough));add('categoryFilter',state.events.map(e=>e.category))}
  function readFilters(){state.filters={q:$('searchFilter').value.trim().toLowerCase(),borough:$('boroughFilter').value,status:$('statusFilter').value,category:$('categoryFilter').value,major:$('majorOnly').checked,photo:$('photoOnly').checked};renderAll()}
  async function fetchJson(url,optional=false){try{const r=await fetch(`${url}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){if(optional)return null;throw e}}
  async function loadData(){$('loadStatus').textContent='Loading live event feeds…';try{const[all,major,delta]=await Promise.all([fetchJson(URLS.all),fetchJson(URLS.major,true),fetchJson(URLS.delta,true)]);state.majorIds.clear();(Array.isArray(major)?major:[]).map(normalize).filter(Boolean).forEach(e=>state.majorIds.add(e.id));state.deltaIds=addedIds(delta||{});state.skipped=0;state.events=(Array.isArray(all)?all:[]).map(row=>{const e=normalize(row);if(!e)state.skipped++;return e}).filter(Boolean);const firstVisit=state.seen.size===0;state.sessionNew.clear();if(!firstVisit)state.events.forEach(e=>{if(!state.seen.has(e.id))state.sessionNew.add(e.id)});state.events.forEach(e=>state.seen.add(e.id));saveSet(KEYS.seen,state.seen);state.loadedAt=new Date();populateFilters();$('loadStatus').textContent=`Live feeds loaded ${state.loadedAt.toLocaleString()}.${firstVisit?' Current feed established as the first-visit baseline.':''}${delta?'':' Delta report unavailable; browser history is still active.'}${state.storage?'':' Browser storage is unavailable, so review tracking will not persist.'}`;if(!state.selectedDate)state.selectedDate=dateKey(new Date());renderAll()}catch(e){$('loadStatus').textContent=`Could not load the primary live event feed: ${e.message}. The calendar cannot render until the feed is reachable.`;$('statusMetrics').hidden=true;$('calendarMonths').replaceChildren(make('div','empty-state','Live event feed unavailable. Use Refresh live data to try again.'))}}
  function bind(){$('previousMonths').addEventListener('click',()=>{state.monthOffset-=2;renderAll()});$('currentMonths').addEventListener('click',()=>{state.monthOffset=0;renderAll()});$('nextMonths').addEventListener('click',()=>{state.monthOffset+=2;renderAll()});$('refreshData').addEventListener('click',loadData);['searchFilter','boroughFilter','statusFilter','categoryFilter','majorOnly','photoOnly'].forEach(id=>$(id).addEventListener(id==='searchFilter'?'input':'change',readFilters));$('clearFilters').addEventListener('click',()=>{['searchFilter','boroughFilter','statusFilter','categoryFilter'].forEach(id=>$(id).value='');$('majorOnly').checked=false;$('photoOnly').checked=false;readFilters()});document.querySelectorAll('[data-status-quick]').forEach(b=>b.addEventListener('click',()=>{$('statusFilter').value=b.dataset.statusQuick;readFilters()}));$('markAllReviewed').addEventListener('click',()=>{filteredEvents().filter(e=>e.date===state.selectedDate).forEach(e=>state.reviewed.add(e.id));saveSet(KEYS.reviewed,state.reviewed);renderAll()})}
  state.seen=loadSet(KEYS.seen);state.reviewed=loadSet(KEYS.reviewed);bind();loadData();
})();