(() => {
'use strict';
const URLS={all:'https://raw.githubusercontent.com/setoxxx/nycif-live-feeds/main/nycif_all_radar_map_events.json',major:'https://raw.githubusercontent.com/setoxxx/nycif-live-feeds/main/nycif_major_radar_map_events.json',delta:'https://raw.githubusercontent.com/setoxxx/nycif-live-feeds/main/data/live_delta_report.json'};
const KEYS={seen:'nycif-assignment-desk-seen-v2',reviewed:'nycif-assignment-desk-reviewed-v2'};
const state={events:[],majorIds:new Set(),deltaIds:new Set(),sessionNew:new Set(),seen:new Set(),reviewed:new Set(),storage:true,monthOffset:0,selectedDate:'',skipped:0,filters:{q:'',borough:'',status:'',category:'',major:false,photo:false}};
const $=id=>document.getElementById(id);const names={new:'New',good:'Strong assignment',review:'Needs review',standard:'Standard'};
function loadSet(k){try{return new Set(JSON.parse(localStorage.getItem(k)||'[]'))}catch{state.storage=false;return new Set()}}
function saveSet(k,s){if(!state.storage)return;try{localStorage.setItem(k,JSON.stringify([...s].slice(-100000)))}catch{state.storage=false}}
function text(v){return String(v??'').trim()} function bool(v){return v===true||v===1||/^(true|yes|1)$/i.test(text(v))}
function first(r,ks){for(const k of ks)if(r?.[k]!==undefined&&r[k]!==null&&text(r[k]))return r[k];return''}
function iso(v){const r=text(v),m=r.match(/^(\d{4}-\d{2}-\d{2})/);if(m)return m[1];const d=new Date(r);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function normalize(r){const date=iso(first(r,['date','start_date','startDate','start_date_time','startDateTime']));if(!date)return null;const title=text(first(r,['title','event_name','eventName']))||'Untitled event',location=text(first(r,['display_location','location','event_location','locationName','address'])),bv=first(r,['borough','event_borough','eventBorough','boroughs']),borough=Array.isArray(bv)?bv.join(', '):text(bv),rawId=first(r,['id','event_id','source_event_id','eventId','sourceEventId']),id=text(rawId)||`${date}|${title}|${location}`.toLowerCase().replace(/\s+/g,' ').slice(0,300);return{id,date,title,location,borough,start:text(first(r,['start_time','startTime'])),end:text(first(r,['end_time','endTime'])),category:text(first(r,['lane','category','event_type','eventType']))||'General',source:text(first(r,['source','source_name','sourceName','source_file','sourceFile']))||'Unknown',verification:text(first(r,['verification_status','verificationStatus'])),priority:Number(first(r,['priority_score','priorityScore']))||0,crowd:text(first(r,['crowd_level','crowdLevel'])),reason:text(first(r,['major_reason','majorReason','review_reason','reviewReason','warning','warnings'])),photo:bool(first(r,['photo_pick','photoPick'])),major:text(first(r,['assignment_feed','assignmentFeed'])).toLowerCase()==='major'||bool(first(r,['field_default','fieldDefault'])),maps:text(first(r,['google_maps_url','googleMapsUrl'])),url:text(first(r,['url','event_url','source_url','sourceUrl']))}}
function collectDeltaIds(d){const s=new Set();for(const r of Array.isArray(d?.added_events)?d.added_events:[]){const n=normalize(r);if(n)s.add(n.id);const x=first(r,['id','event_id','source_event_id','eventId']);if(text(x))s.add(text(x))}return s}
function needsReview(e){return !e.title||e.title==='Untitled event'||!e.location||!e.borough||/(review|uncertain|unverified|pending|rejected|quarantine|warning|invalid)/.test(`${e.verification} ${e.reason}`.toLowerCase())}
function isGood(e){return e.major||state.majorIds.has(e.id)||e.photo||e.priority>=80||!!e.reason||/(field.intel|verified|confirmed|nypd)/.test(e.verification.toLowerCase())}
function status(e){if(!state.reviewed.has(e.id)&&(state.deltaIds.has(e.id)||state.sessionNew.has(e.id)))return'new';if(needsReview(e))return'review';if(isGood(e))return'good';return'standard'}
function currentMonth(){const n=new Date();return new Date(n.getFullYear(),n.getMonth()+state.monthOffset,1)}
function key(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function filtered(){const f=state.filters;return state.events.filter(e=>{const h=`${e.title} ${e.location} ${e.borough} ${e.source} ${e.category}`.toLowerCase();return(!f.q||h.includes(f.q))&&(!f.borough||e.borough===f.borough)&&(!f.category||e.category===f.category)&&(!f.status||status(e)===f.status)&&(!f.major||e.major||state.majorIds.has(e.id))&&(!f.photo||e.photo)})}
function grouped(rows){const m=new Map();for(const e of rows){if(!m.has(e.date))m.set(e.date,[]);m.get(e.date).push(e)}for(const a of m.values())a.sort((x,y)=>`${x.start} ${x.title}`.localeCompare(`${y.start} ${y.title}`));return m}
function el(t,c,v){const n=document.createElement(t);if(c)n.className=c;if(v!==undefined)n.textContent=v;return n}
function esc(v){return text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderMonth(){const rows=filtered(),map=grouped(rows),start=currentMonth(),root=$('calendarMonth');root.replaceChildren();$('monthTitle').textContent=start.toLocaleDateString([],{month:'long',year:'numeric'});const monthPrefix=`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,'0')}`;const monthRows=rows.filter(e=>e.date.startsWith(monthPrefix));$('monthSummary').textContent=`${monthRows.length.toLocaleString()} matching events this month`;const days=el('div','weekday-row');['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].forEach(x=>days.append(el('div','weekday',x)));root.append(days);const grid=el('div','month-grid'),firstDay=new Date(start.getFullYear(),start.getMonth(),1),last=new Date(start.getFullYear(),start.getMonth()+1,0),cursor=new Date(firstDay);cursor.setDate(cursor.getDate()-firstDay.getDay());const end=new Date(last);end.setDate(end.getDate()+(6-last.getDay()));const today=key(new Date());while(cursor<=end){const k=key(cursor),items=map.get(k)||[],b=el('button','day-cell');b.type='button';b.dataset.date=k;b.setAttribute('aria-label',`${cursor.toLocaleDateString([],{month:'long',day:'numeric',year:'numeric'})}: ${items.length} events`);if(cursor.getMonth()!==start.getMonth())b.classList.add('other-month');if(k===today)b.classList.add('today');if(k===state.selectedDate)b.classList.add('selected');const top=el('div','day-top');top.append(el('span','day-number',cursor.getDate()),el('span','event-count',`${items.length} event${items.length===1?'':'s'}`));b.append(top);items.slice(0,4).forEach(e=>{const s=status(e);b.append(el('span',`event-chip ${s}`,`${s==='new'?'NEW · ':''}${e.start?e.start+' · ':''}${e.title}`))});if(items.length>4)b.append(el('span','more-label',`+ ${items.length-4} more`));b.addEventListener('click',()=>{state.selectedDate=k;renderAll();$('dailyEvents').scrollIntoView({behavior:'smooth',block:'start'})});grid.append(b);cursor.setDate(cursor.getDate()+1)}root.append(grid);renderMetrics(monthRows)}
function card(e){const s=status(e),a=el('article',`event-card ${s}`),h=el('div','event-card-header');h.append(el('h3','',e.title),el('span',`status-label ${s}`,names[s]));a.append(h);const meta=el('div','event-meta');[['Time',[e.start,e.end].filter(Boolean).join('–')||'Time not listed'],['Borough',e.borough||'Missing'],['Location',e.location||'Missing'],['Category',e.category],['Source',e.source],['Verification',e.verification||'Not listed'],['Priority',e.priority||'—'],['Crowd',e.crowd||'—'],['Assignment reason',e.reason||'—']].forEach(([k,v])=>{const d=el('div','');d.innerHTML=`<strong>${esc(k)}:</strong> ${esc(v)}`;meta.append(d)});a.append(meta);const actions=el('div','event-actions');if(e.maps){const x=el('a','','Open map');x.href=e.maps;x.target='_blank';x.rel='noopener noreferrer';actions.append(x)}if(e.url){const x=el('a','','Open source');x.href=e.url;x.target='_blank';x.rel='noopener noreferrer';actions.append(x)}const reviewed=state.reviewed.has(e.id),b=el('button','',reviewed?'Reviewed in this browser':'Mark reviewed');b.type='button';b.disabled=reviewed;b.addEventListener('click',()=>{state.reviewed.add(e.id);saveSet(KEYS.reviewed,state.reviewed);renderAll()});actions.append(b);a.append(actions);return a}
function renderDay(){const root=$('dailyEvents');root.replaceChildren();if(!state.selectedDate){root.append(el('div','empty-state','Select a date to view assignments.'));$('markAllReviewed').disabled=true;return}const rows=filtered().filter(e=>e.date===state.selectedDate),d=new Date(`${state.selectedDate}T12:00:00`);$('dayLabel').textContent=d.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('daySummary').textContent=`${rows.length} matching assignment${rows.length===1?'':'s'} on this date.`;$('markAllReviewed').disabled=!rows.length;if(!rows.length){root.append(el('div','empty-state','No assignments match the active filters for this date.'));return}rows.forEach(e=>root.append(card(e)))}
function renderMetrics(monthRows){const counts={new:0,good:0,review:0,standard:0};monthRows.forEach(e=>counts[status(e)]++);const values=[['Loaded',state.events.length],['This month',monthRows.length],['New',counts.new],['Strong',counts.good],['Needs review',counts.review],['Standard',counts.standard],['Skipped',state.skipped]],root=$('statusMetrics');root.hidden=false;root.replaceChildren();values.forEach(([k,v])=>{const m=el('div','metric');m.append(el('strong','',Number(v).toLocaleString()),el('span','',k));root.append(m)})}
function renderAll(){renderMonth();renderDay()}
function populate(){const add=(id,vals)=>{const s=$(id),cur=s.value;while(s.options.length>1)s.remove(1);[...new Set(vals.filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.append(o)});s.value=cur};add('boroughFilter',state.events.map(e=>e.borough));add('categoryFilter',state.events.map(e=>e.category))}
function readFilters(){state.filters={q:$('searchFilter').value.trim().toLowerCase(),borough:$('boroughFilter').value,status:$('statusFilter').value,category:$('categoryFilter').value,major:$('majorOnly').checked,photo:$('photoOnly').checked};renderAll()}
async function fetchJson(u,optional=false){try{const r=await fetch(`${u}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){if(optional)return null;throw e}}
async function load(){$('loadStatus').textContent='Loading live event feeds…';try{const[all,major,delta]=await Promise.all([fetchJson(URLS.all),fetchJson(URLS.major,true),fetchJson(URLS.delta,true)]);state.majorIds.clear();(Array.isArray(major)?major:[]).map(normalize).filter(Boolean).forEach(e=>state.majorIds.add(e.id));state.deltaIds=collectDeltaIds(delta||{});state.skipped=0;state.events=(Array.isArray(all)?all:[]).map(r=>{const e=normalize(r);if(!e)state.skipped++;return e}).filter(Boolean);const firstVisit=state.seen.size===0;state.sessionNew.clear();if(!firstVisit)state.events.forEach(e=>{if(!state.seen.has(e.id))state.sessionNew.add(e.id)});state.events.forEach(e=>state.seen.add(e.id));saveSet(KEYS.seen,state.seen);populate();if(!state.selectedDate)state.selectedDate=key(new Date());$('loadStatus').textContent=`Live feeds loaded ${new Date().toLocaleString()}.${firstVisit?' Current feed established as the first-visit baseline.':''}${delta?'':' Delta report unavailable.'}${state.storage?'':' Browser storage unavailable; review tracking will not persist.'}`;renderAll()}catch(e){$('loadStatus').textContent=`Could not load the primary live event feed: ${e.message}`;$('statusMetrics').hidden=true;$('calendarMonth').replaceChildren(el('div','empty-state','Live event feed unavailable. Use Refresh live data to try again.'))}}
function bind(){$('previousMonth').addEventListener('click',()=>{state.monthOffset--;renderAll()});$('todayMonth').addEventListener('click',()=>{state.monthOffset=0;state.selectedDate=key(new Date());renderAll()});$('nextMonth').addEventListener('click',()=>{state.monthOffset++;renderAll()});$('refreshData').addEventListener('click',load);['searchFilter','boroughFilter','statusFilter','categoryFilter','majorOnly','photoOnly'].forEach(id=>$(id).addEventListener(id==='searchFilter'?'input':'change',readFilters));$('clearFilters').addEventListener('click',()=>{['searchFilter','boroughFilter','statusFilter','categoryFilter'].forEach(id=>$(id).value='');$('majorOnly').checked=false;$('photoOnly').checked=false;readFilters()});$('markAllReviewed').addEventListener('click',()=>{filtered().filter(e=>e.date===state.selectedDate).forEach(e=>state.reviewed.add(e.id));saveSet(KEYS.reviewed,state.reviewed);renderAll()})}
state.seen=loadSet(KEYS.seen);state.reviewed=loadSet(KEYS.reviewed);bind();load();
})();